---
language: ruby
sudo: false
cache: bundler
script: "bundle exec rake ci"
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby
  - jruby-9000
  - rbx-3.60
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx-3.60
  fast_finish: true
branches:
  only: master
notifications:
  email: false
